### ISSUE TITLE
More Help :3

### ISSUE THREAD

**Issue by AmineMessabhia** [cgio/darkxd#1]
Hey, Changing the colors hex by hex is a bit tiring, can you pretty please upload us here your own General.xaml file? It would be a huge help, and you'd save me and others a huge amount of time.

Thanks.

**Comment by cgio** [comment]
Hi! The screenshot in the repo is from the default "Light" to "Dark" text change described in step eight. No need to change individual colors unless you want detailed customization. 

I would post the General.xaml, but the file's confidentiality clause prohibits such activity :)

**Comment by cgio** [comment]
Hi Amine. I changed the approach. It's more simple via a General.xaml dark theme file. Please check README.md again. If you have a chance, let me know if it works for you.

**Comment by AmineMessabhia** [comment]
Hey cgio, Thanks for the reply, i did download the file, and it works, only little problem, is the background, that also needs to be changed to some darker grey, but it's not much, just one hex to change, and it'll be done, Thank you again!

**Comment by cgio** [comment]
Thanks for the feedback! Yes, although I have figured out how to make an artboard default to black (not yet reflected in the repo and is accomplished by editing a different file), addressing the light grey "canvas" color proves to be more elusive (or non-responsive). If I figure it out or anyone else does, I shall update the repo.

**Comment by AmineMessabhia** [comment]
Thank you for your hard work!
