### ISSUE TITLE
Not working on version 32.0.22.11

### ISSUE THREAD

**Issue by RikudouRay** [cgio/darkxd#10]
App is force close, and restoring the General.xaml will not work. It will need to restore the whole themes folder for it to work.

**Comment by cgio** [comment]
Apologies for the delay. Life has been busy.

Please see the updated link to the new General.xaml in README.md or use the direct URL [https://www.dropbox.com/s/62elsglx8wl8rdq/General.zip?dl=0](https://www.dropbox.com/s/62elsglx8wl8rdq/General.zip?dl=0).

**Comment by RikudouRay** [comment]
Thanks man really appreciate it! I've been playing around recently with the hue of the icons and I also learned that we can change the color of the layers panel too. 

>     
>     <Color x:Key="SpColorLayerItemText">#3F3F3F</Color>
>     <Color x:Key="SpColorLayerRowInEditContext">#FFFFFF</Color>
>     <SolidColorBrush x:Key="SpBrushLayerRowHiglightHovered" Color="#3b3b3b"/>
>     <SolidColorBrush x:Key="SpBrushLayerRowHiglightPressed" Color="#3b3b3b"/>
>     <SolidColorBrush x:Key="SpBrushLayerRowHiglightSelected" Color="#262626"/>
>     <SolidColorBrush x:Key="SpBrushLayerRowHiglightSelectedHovered" Color="#3b3b3b"/>
>     <SolidColorBrush x:Key="SpBrushLayerRowHiglightSelectedPressed" Color="#3b3b3b"/>


The only section that I cannot find in the General.xaml is the [Assets Panel and Color Picker](https://www.imageupload.net/image/ksX7t)
