### ISSUE TITLE
Not working or just me?

### ISSUE THREAD

**Issue by smbt** [cgio/darkxd#2]
Hey, thanks alot for this very in detail guide.

Let say that there is said `General.xaml` and at some position near the top the word `Light` could be seen. I could changed this word to `Dark`. Now my XD could not start anymore... I could change it back and the program could start up properly. Would I be doing something wrong or could this not be working anymore?

Thanks for any hints or confirmation from users with the same experience.

**Comment by smbt** [comment]
Alright it seems I did not change the other `Dark` to `Light`. It´s opening now but no changes applied...

**Comment by smbt** [comment]
Ok... the Dark-mode doesn´t apply to the initial screen so I was too quick to think no colors changed. Still not very much of the interface is dark and the low contrasts and still bright select boxes make it not very comfortable to work with. I couldn´t get individual color changes to be applied either.

I guess it´s back to the Light-mode then. Hope this feature is being implemented by Adobe soon.

**Comment by cgio** [comment]
Hello! I changed the approach. It's more simple via a General.xaml dark theme file. I made a number of changes to beautify and enhance contrast. Please check README.md again. If you have a chance, let me know if it works for you.
