### ISSUE TITLE
Adobe XD Crashes When the Custom `general.xaml` File is Given

### ISSUE THREAD

**Issue by GalGreenfield** [cgio/darkxd#3]
I followed the tutorial - thank you for the detailed and clearly-written steps. :)

However, this doesn't work for me - XD crashes after I supply it with the custom `general.xaml` dark theme file.

What happens is that I open up XD, it displays a  blank Windows window with the upper menu interaction buttons (close, minimize, maximize), and then after a few second it crashes, without any animations - the winodw just disappears.

I'm running the latest version of XD at the current time of writing this on Windows 10 Pro, 64-bit.

Could you please help me solve this issue? If there's any information I could provide you like logs, please let me know.

**Comment by makindajackson** [comment]
same here

**Comment by Jordan-foodmigo** [comment]
Same, please fix.

**Comment by cgio** [comment]
Should now be fixed. Download the new General.xaml linked to in README.md. 

For installation, you can probably replace the outdated General.xaml with the new one to fix the crash. Note that you may have to follow the file permission instructions.

Crash reason - the Adobe XD team changed a few things. The old General.xaml is incompatible. To fix this issue, I diffed a clean/new General.xaml with the previous/customized one, made changes progressively, tested, and repeated to ensure stability.

Let me know if it works for you and I'll close this. 

Thanks!

**Comment by Exoplanet3000** [comment]
> Should now be fixed. Download the new General.xaml linked to in README.md. Make sure you're using Adobe XD 19.2.22.3 which is the latest at the time of writing.
> 
> For installation, you can probably replace the outdated General.xaml with the new one to fix the crash. Note that you may have to follow the file permission instructions.
> 
> Crash reason - the Adobe XD team changed a few things. The old General.xaml is incompatible. To fix this issue, I diffed a clean/new General.xaml with the previous/customized one, made changes progressively, tested, and repeated to ensure stability.
> 
> Let me know if it works for you and I'll close this.
> 
> Thanks!

Can conform it works :) 
Thank you !

**Comment by makindajackson** [comment]
it works but still crashes

**Comment by makindajackson** [comment]
> Should now be fixed. Download the new General.xaml linked to in README.md. Make sure you're using Adobe XD 19.2.22.3 which is the latest at the time of writing.
> 
> For installation, you can probably replace the outdated General.xaml with the new one to fix the crash. Note that you may have to follow the file permission instructions.
> 
> Crash reason - the Adobe XD team changed a few things. The old General.xaml is incompatible. To fix this issue, I diffed a clean/new General.xaml with the previous/customized one, made changes progressively, tested, and repeated to ensure stability.
> 
> Let me know if it works for you and I'll close this.
> 
> Thanks!

I also need authentication to participate in this project( XD themeing not only dark theme but also others) 

I managed to work with XAML file (had some themed xaml files but still working on them)

thanks. #credits to the owner(for this idea)

**Comment by cgio** [comment]
@makindajackson:

Adobe XD can behave a bit odd at times. You may have to use the Adobe cleaning utility and/or uninstall and reinstall XD, grant ownership of the XD directory, and test if XD works without crashing prior to making any modifications to the original General.xaml that is provided with a new install. If XD does not crash, then proceed with my instructions at your own risk. Also, make sure you're actually using the new General.xaml and not the old version.

As for your request to work on this project, feel free to borrow my instructions for your own repository, or fork this, etc. If there is enough interest and alternative user themes are decent, I may or may not link to them in this repository's README.md.

I am going to close this, as confirmation was provided that this is working in addition to my own testing.

**Comment by makindajackson** [comment]
> @makindajackson:
> 
> Adobe XD can behave a bit odd at times. You may have to use the Adobe cleaning utility and/or uninstall and reinstall XD, grant ownership of the XD directory, and test if XD works without crashing prior to making any modifications to the original General.xaml that is provided with a new install. If XD does not crash, then proceed with my instructions at your own risk. Also, make sure you're actually using the new General.xaml and not the old version.
> 
> As for your request to work on this project, feel free to borrow my instructions for your own repository, or fork this, etc. If there is enough interest and alternative user themes are decent, I may or may not link to them in this repository's README.md.
> 
> I am going to close this, as confirmation was provided that this is working in addition to my own testing.

ok, thanks

**Comment by divmonkey** [comment]
It's not working again, loaded the backup general.xaml  in and it doesn't work, I mean it broke the xd. So, I have to reinstall XD. Wish there's a new version of this. Love to have a dark mode of XD.

**Comment by cgio** [comment]
> 
> 
> It's not working again, loaded the backup general.xaml in and it doesn't work, I mean it broke the xd. So, I have to reinstall XD. Wish there's a new version of this. Love to have a dark mode of XD.

Try the updated version please and let me know. Thanks!

**Comment by divmonkey** [comment]
> 
> 
> > It's not working again, loaded the backup general.xaml in and it doesn't work, I mean it broke the xd. So, I have to reinstall XD. Wish there's a new version of this. Love to have a dark mode of XD.
> 
> Try the updated version please and let me know. Thanks!

SI got the lastest XD which just got updated today really. And have tried it again. It crashes again, XD never boot up. 
![image](https://user-images.githubusercontent.com/11624288/73298186-d57be800-4247-11ea-9f98-481f0214b256.png)
