### ISSUE TITLE
App Crash While Clicking on Rename/Select Location Option

### ISSUE THREAD

**Issue by TCORPORAT** [cgio/darkxd#4]
Hi,
After creating a new file, the top center option to select location (Local/Cloud) with "rename file" is clicked , the whole app crashes and have to manually Rename the file, forget changing location, so currently the workaround i found was copy an existing xd file, rename it & then open it to save it on local storage.
Hope this will be fixed soon & thank you for this amazing eye reliever!

**Comment by cgio** [comment]
Hi. Can you please describe your problem in greater detail? Currently, the description you provided resembles an issue with navigating the Windows OS or a bug within XD itself that is unrelated to this dark theme project.

**Comment by TCORPORAT** [comment]
Ok, in center header of adobe XD , file name created by default is "Untitled" with cloud icon next to it...that's the one on which clicking (in dark mode ) causes entire application to crash and disappear...verified this via putting back the orignal "General.xml" file...so pls see that something in your modified file is causing this.

**Comment by Wilzzu** [comment]
Hey,
I'm having the same issue. The program also crashes when I try saving my project using "Save As". Always have to use the original xml file to rename and save projects.

**Comment by cgio** [comment]
I have tested both with the update I made today (see README.md) and no instability issues for either action (Save As or clicking the text near the cloud icon). The update is for Adobe XD 25.3.12.1.
