### ISSUE TITLE
Crashes in 31.1.12

### ISSUE THREAD

**Issue by KorbsStudio** [cgio/darkxd#5]
When opening a project, the app crashes.

**Comment by chaosnhatred** [comment]
Fixed!
added screen shots and a link to the update xaml

![about](https://user-images.githubusercontent.com/1500273/67169830-f6e15400-f37b-11e9-9647-86891766639b.JPG)****

![main](https://user-images.githubusercontent.com/1500273/67169842-095b8d80-f37c-11e9-8a71-1d6598c06283.JPG)

[general.xaml](https://www.dropbox.com/s/zb5qtzqko5hhya2/General.zip?dl=0)

**Comment by jkmartindale** [comment]
Seems to be working on my end as well. Can you update the link in README.md?

![image](https://user-images.githubusercontent.com/11380394/68078736-95bd7580-fdaa-11e9-9407-d780a5f8b128.png)

**Comment by michaelperrygoodman** [comment]
My XD is the same version (23.1.32.2) and it continues to crash. Only the original XAML file will work

**Comment by ygtalp** [comment]
Thanks for your efforts. you protect our eyes swh. I'm waiting for the new version to be fixed. 
v@24.4.22

**Comment by KorbsStudio** [comment]
Has this been fixed yet?! I see the issue is still opened.

**Comment by michaelperrygoodman** [comment]
This was closed but it is still broken for me.

**Comment by jkmartindale** [comment]
@michaelperrygoodman what version of XD are you using?

**Comment by michaelperrygoodman** [comment]
@jkmartindale 24.4.22.1 which I guess is a separate issue now due to version number

**Comment by KorbsStudio** [comment]
27.1.12.4 is the latest version and it's working fine now

**Comment by KorbsStudio** [comment]
The issue has returned in version 31.1.12

**Comment by aninv18** [comment]
How can we make the background of the workspace also grey or black?

**Comment by KorbsStudio** [comment]
> How can we make the background of the workspace also grey or black?

Don't. That is not a good idea.

**Comment by aninv18** [comment]
> > How can we make the background of the workspace also grey or black?
> 
> Don't. That is not a good idea.

why not??

**Comment by cgio** [comment]
Updated for Adobe XD 31.1.12.13: see new General.zip/General.xaml download link in README.md. Let me know if it works for you. Thanks.

**Comment by KorbsStudio** [comment]
Thanks, it's working now!

**Comment by cgio** [comment]
> 
> 
> How can we make the background of the workspace also grey or black?

As mentioned in README.md, some elements are not controlled by General.xaml, such as the workspace area you refer to. The color of that area, rgb(228, 228, 228), is uncommon in UWP apps. Further, a Microsoft diagnostic app called Accessibility Insights identifies the area in question as custom control type. The area/control type is without a FillType property and any other property that has a configurable color setting for setting the area to a darker color. The AutomationId property for this custom control is "canvasView". That's a string/clue you could use to search other files, which may include binaries. This Microsoft page may provide some ideas for digging deeper: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-regcustompropseventpatterns.
