### ISSUE TITLE
The dropbox link doesn't work (Error 404 from Dropbox)

### ISSUE THREAD

**Issue by martinsstuff** [cgio/darkxd#7]

**Comment by bdotq** [comment]
+1
why wasnt the xaml just uploaded to this github?

**Comment by cgio** [comment]
> 
> 
> +1
> why wasnt the xaml just uploaded to this github?

Precautionary measure; better to have an Adobe takedown/cease/desist request served to Dropbox than a personal GitHub.

Try this: https://www.dropbox.com/s/usdsks0mx1lvzin/General.zip?dl=0

**Comment by martinsstuff** [comment]
Does Adobe have a history of doing this or is just a general precautionary measure?

(Asking in case I ever want to do this sort of project myself)

**Comment by cgio** [comment]
> 
> 
> Does Adobe have a history of doing this or is just a general precautionary measure?
> 
> (Asking in case I ever want to do this sort of project myself)

On a separate more personal website, for multiple years, I operated a similar free community-oriented "service" for a popular non-Adobe PC and Mac app. This application required patching the app's executable binary file (perhaps considered a more serious offense by some) thus unblocking the app's ability to perform a very useful function for a sizeable portion of users. I never received any negative communications from the popular software company despite years of offering that free service. Positive blogs posts, etc. were written about the instructional service I freely provided.

Considering XD's competition, my sense is that XD's first priority is maximizing user adoption. The last thing they should be doing is hurting users (who picked or have to work with their platform) for a preference fix (dark theme). Plus, XD's development team has not tackled the dark theme for years; perhaps they're understaffed/underfunded.

That said, for all I know, tomorrow, someone at Adobe could call in a favor @ GitHub/MSFT to pull my stuff. I don't really trust [large] [companies] more than I have to. 

Hope you can see my thought process. Thanks for asking a good question, especially as related to software and company IP/EULA/legal application interests!
